### ISSUE TITLE
Timestamp JSON serialization incorrect

### ISSUE THREAD

**Issue by noahseger** [tatethurston/ProtoScript#39]
https://github.com/tatethurston/ProtoScript/blob/main/packages/protoscript/src/runtime/well-known-types/timestamp.pb.ts#L231-L238

The client marshals the Timestamp as an object, but it should be an ISO-8601 date:

```
Timestamp | string | "1972-01-01T10:00:20.021Z" | Uses RFC 3339, where generated output will always be Z-normalized and uses 0, 3, 6 or 9 fractional digits. Offsets other than "Z" are also accepted.
-- | -- | -- | --

```

https://protobuf.dev/programming-guides/proto3/#json

We confirmed after patching this method that the message is accepted by the server:

```ts
import { Timestamp, TimestampJSON } from "protoscript";

TimestampJSON._writeMessage = (msg: Partial<Timestamp>): Record<string, unknown> => {
  const date = new Date(Number(msg.seconds) * 1_000 + (msg.nanos ?? 0 / 1_000_000));
  return date.toISOString() as any;
};
```

**Comment by tatethurston** [comment]
@noahseger Can you share more about the server you're interacting with? Happy to make this update, but I'm under the impression that serializers are expected to accept both the "well known" and the "expanded" formats.

**Comment by noahseger** [comment]
Thanks for checking @tatethurston ! We are using a few different server runtimes, but this one failed with Google's Java protoc. I can run a few tests to see if there are differences in compatibility.

I love the `Date` idea, and would be way easier to deal with on clients/servers — sounds like it would have to be an opt-in protoc option though? In the meantime, shipping a util in the runtime like https://cloud.google.com/java/docs/reference/protobuf/latest/com.google.protobuf.util.Timestamps would be compatible and helpful.

**Comment by tatethurston** [comment]
https://github.com/tatethurston/ProtoScript/issues/43

**Comment by noahseger** [comment]
Thanks again! We're not blocked, but will watch for a release.
