### ISSUE TITLE
Use ["property"] access for JSON objects

### ISSUE THREAD

**Issue by DavidSouther** [tatethurston/ProtoScript#4]
Using .property access for json is not resistant to code minification tools. Consider using ["property"] access for JSON instead.

**Comment by tatethurston** [comment]
Hey @DavidSouther thanks for opening this. I'm not aware of any minification tools that perform property mangling out of the box. [Terser has an opt-in option](https://github.com/terser/terser#cli-mangling-property-names---mangle-props). Is this theoretical or do you have a use case already? If it's the later, could you share the minification tool you're using? Either way, happy to look into this, I think the change will be relatively small, just want to make sure I'm understanding the desired outcome correctly.

**Comment by DavidSouther** [comment]
Closure Compiler ([jscompiler](https://developers.google.com/closure/compiler)) advanced optimizations does property mangling by default. It's hard to find details on usage because it's usually included outside of the npm ecosystem via Maven, and of course inside Google it's all jscompiler.

**Comment by tatethurston** [comment]
Thanks -- I'll setup a minimal example using the closure compiler and take a look

**Comment by tatethurston** [comment]
This closure compiler bug https://github.com/google/closure-compiler/issues/3944 prevents using advanced optimizations on protoscript. Specifically, the usage of static class properties in the protoscript runtime is problematic for the closure compiler.

```
    yarn google-closure-compiler 'src/*.js' 'node_modules/protoscript/index.js' 'node_modules/protoscript/runtime/**/*.js' 'node_modules/protoscript/runtime/*.js' --js_output_file dist/index.js --language_in UNSTABLE --language_out UNSTABLE --module_resolution=NODE --compilation_level ADVANCED
```
